version: '3.9'

services:
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - 20000:20000
    # env_file:
    #   - ./api/.env
    depends_on:
      - db
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    build: ./database
    restart: unless-stopped
    # env_file:
    #   - ./database/.env
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:latest
    ports:
      - 20001:20001
    environment:
      MONGO_INITDB_DATABASE: kuudra
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null --port 20001

networks:
  default:
    driver: bridge

volumes:
  mongo-data: {}