export enum ItemCategory {
    Shard = 'SHARD',
    Armor = 'ARMOR',
    Weapon = 'WEAPON',
    Sword = 'SWORD',
    Bow = 'BOW',
    Equipment = 'EQUIPMENT',
    Rod = 'ROD',
}

export enum ItemFamily {
    Kuudra = 'KUUDRA',
    Molten = 'MOLTEN',
    Vanquished = 'VANQUISHED',
}

export enum ItemType {
    Helmet = 'HELMET',
    Chestplate = 'CHESTPLATE',
    Leggings = 'LEGGINGS',
    Boots = 'BOOTS',
    Necklace = 'NECKLACE',
    Cloak = 'CLOAK',
    Belt = 'BELT',
    Gloves = 'GLOVES',
    Bracelet = 'BRACELET',
}

export const ATTRIBUTE_NICKNAME_MAPPINGS = {
    mp: 'mana_pool',
    fs: 'fishing_speed',
    fe: 'fishing_experience',
    th: 'trophy_hunter',
    dh: 'double_hook',
    bh: 'blazing_fortune',
    mr: 'mana_regeneration',
    mf: 'magic_find',
    dom: 'dominance',
    vit: 'vitality',
    vet: 'veteran',
    ll: 'lifeline',
};

export const ITEM_NAME_MAPPINGS = {
    'Hellfire Rod': 'HELLFIRE_ROD',
    'Magma Rod': 'MAGMA_ROD',
    'Inferno Rod': 'INFERNO_ROD',
    'Slug Boots': 'SLUG_BOOTS',
    'Shimmering Light Slippers': 'SHIMMERING_LIGHT_SLIPPERS',
    'Vanquished Ghast Cloak': 'VANQUISHED_GHAST_CLOAK',
    'Staff of the Volcano': 'STAFF_OF_THE_VOLCANO',
    'Flaming Chestplate': 'FLAMING_CHESTPLATE',
    'Vanquished Glowstone Gauntlet': 'VANQUISHED_GLOWSTONE_GAUNTLET',
    'Molten Necklace': 'MOLTEN_NECKLACE',
    'Ghast Cloak': 'GHAST_CLOAK',
    'Magma Lord Boots': 'MAGMA_LORD_BOOTS',
    'Fire Fury Staff': 'FIRE_FURY_STAFF',
    'Sulphur Bow': 'SULPHUR_BOW',
    'Magma Lord Helmet': 'MAGMA_LORD_HELMET',
    'Delirium Necklace': 'DELIRIUM_NECKLACE',
    'Implosion Belt': 'IMPLOSION_BELT',
    'Shimmering Light Trousers': 'SHIMMERING_LIGHT_TROUSERS',
    'Ragnarock Axe': 'RAGNAROCK_AXE',
    'Magma Lord Chestplate': 'MAGMA_LORD_CHESTPLATE',
    'Fire Veil Wand': 'FIRE_VEIL_WAND',
    'Molten Bracelet': 'MOLTEN_BRACELET',
    'Gauntlet of Contagion': 'GAUNTLET_OF_CONTAGION',
    'Vanquished Blaze Belt': 'VANQUISHED_BLAZE_BELT',
    'Magma Lord Leggings': 'MAGMA_LORD_LEGGINGS',
    'Scourge Cloak': 'SCOURGE_CLOAK',
    'Blaze Belt': 'BLAZE_BELT',
    'Scoville Belt': 'SCOVILLE_BELT',
    'Berserker Chestplate': 'BERSERKER_CHESTPLATE',
    'Fire Freeze Staff': 'FIRE_FREEZE_STAFF',
    'Flaming Fist': 'FLAMING_FIST',
    'Berserker Boots': 'BERSERKER_BOOTS',
    'Berserker Leggings': 'BERSERKER_LEGGINGS',
    'Berserker Helmet': 'BERSERKER_HELMET',
    'Sword of Bad Health': 'SWORD_OF_BAD_HEALTH',
    'Taurus Helmet': 'TAURUS_HELMET',
    'Vanquished Magma Necklace': 'VANQUISHED_MAGMA_NECKLACE',
    'Blade of the Volcano': 'BLADE_OF_THE_VOLCANO',
    'Molten Belt': 'MOLTEN_BELT',
    'Glowstone Gauntlet': 'GLOWSTONE_GAUNTLET',
    'Lava Shell Necklace': 'LAVA_SHELL_NECKLACE',
    'Wand of Strength': 'WAND_OF_STRENGTH',
    'Shimmering Light Tunic': 'SHIMMERING_LIGHT_TUNIC',
    'Magma Necklace': 'MAGMA_NECKLACE',
    'Shimmering Light Hood': 'SHIMMERING_LIGHT_HOOD',
    'Molten Cloak': 'MOLTEN_CLOAK',
    'Moogma Leggings': 'MOOGMA_LEGGINGS',
    'Attribute Shard': 'ATTRIBUTE_SHARD',
    'Terror Helmet': 'TERROR_HELMET',
    'Terror Leggings': 'TERROR_LEGGINGS',
    'Terror Boots': 'TERROR_BOOTS',
    'Terror Chestplate': 'TERROR_CHESTPLATE',
    'Crimson Helmet': 'CRIMSON_HELMET',
    'Crimson Chestplate': 'CRIMSON_CHESTPLATE',
    'Crimson Leggings': 'CRIMSON_LEGGINGS',
    'Crimson Boots': 'CRIMSON_BOOTS',
    'Aurora Leggings': 'AURORA_LEGGINGS',
    'Aurora Boots': 'AURORA_BOOTS',
    'Aurora Helmet': 'AURORA_HELMET',
    'Aurora Chestplate': 'AURORA_CHESTPLATE',
    'Hollow Wand': 'HOLLOW_WAND',
    'Hollow Leggings': 'HOLLOW_LEGGINGS',
    'Hollow Chestplate': 'HOLLOW_CHESTPLATE',
    'Hollow Boots': 'HOLLOW_BOOTS',
    'Hollow Helmet': 'HOLLOW_HELMET',
    'Fervor Leggings': 'FERVOR_LEGGINGS',
    'Fervor Helmet': 'FERVOR_HELMET',
    'Fervor Boots': 'FERVOR_BOOTS',
    'Fervor Chestplate': 'FERVOR_CHESTPLATE',
    'Thunder Chestplate': 'THUNDER_CHESTPLATE',
    'Thunder Helmet': 'THUNDER_HELMET',
    'Thunder Leggings': 'THUNDER_LEGGINGS',
    'Thunder Boots': 'THUNDER_BOOTS',
    'Thunderbolt Necklace': 'THUNDERBOLT_NECKLACE',
};

export const ITEM_METADATA: Record<
    string,
    { category: ItemCategory; type?: ItemType; family?: ItemFamily }
> = {
    ATTRIBUTE_SHARD: { category: ItemCategory.Shard },
    AURORA_BOOTS: {
        category: ItemCategory.Armor,
        type: ItemType.Boots,
        family: ItemFamily.Kuudra,
    },
    AURORA_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
        family: ItemFamily.Kuudra,
    },
    AURORA_HELMET: {
        category: ItemCategory.Armor,
        type: ItemType.Helmet,
        family: ItemFamily.Kuudra,
    },
    AURORA_LEGGINGS: {
        category: ItemCategory.Armor,
        type: ItemType.Leggings,
        family: ItemFamily.Kuudra,
    },
    BERSERKER_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    BERSERKER_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
    },
    BERSERKER_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    BERSERKER_LEGGINGS: {
        category: ItemCategory.Armor,
        type: ItemType.Leggings,
    },
    BLADE_OF_THE_VOLCANO: { category: ItemCategory.Weapon },
    BLAZE_BELT: { category: ItemCategory.Equipment, type: ItemType.Belt },
    CRIMSON_BOOTS: {
        category: ItemCategory.Armor,
        type: ItemType.Boots,
        family: ItemFamily.Kuudra,
    },
    CRIMSON_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
        family: ItemFamily.Kuudra,
    },
    CRIMSON_HELMET: {
        category: ItemCategory.Armor,
        type: ItemType.Helmet,
        family: ItemFamily.Kuudra,
    },
    CRIMSON_LEGGINGS: {
        category: ItemCategory.Armor,
        type: ItemType.Leggings,
        family: ItemFamily.Kuudra,
    },
    DELIRIUM_NECKLACE: {
        category: ItemCategory.Equipment,
        type: ItemType.Necklace,
    },
    FERVOR_BOOTS: {
        category: ItemCategory.Armor,
        type: ItemType.Boots,
        family: ItemFamily.Kuudra,
    },
    FERVOR_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
        family: ItemFamily.Kuudra,
    },
    FERVOR_HELMET: {
        category: ItemCategory.Armor,
        type: ItemType.Helmet,
        family: ItemFamily.Kuudra,
    },
    FERVOR_LEGGINGS: {
        category: ItemCategory.Armor,
        type: ItemType.Boots,
        family: ItemFamily.Kuudra,
    },
    FIRE_FREEZE_STAFF: { category: ItemCategory.Weapon },
    FIRE_FURY_STAFF: { category: ItemCategory.Weapon },
    FIRE_VEIL_WAND: { category: ItemCategory.Weapon },
    FLAMING_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
    },
    FLAMING_FIST: { category: ItemCategory.Equipment, type: ItemType.Gloves },
    GAUNTLET_OF_CONTAGION: {
        category: ItemCategory.Equipment,
        type: ItemType.Gloves,
    },
    GHAST_CLOAK: { category: ItemCategory.Equipment, type: ItemType.Cloak },
    GLOWSTONE_GAUNTLET: {
        category: ItemCategory.Equipment,
        type: ItemType.Gloves,
    },
    HELLFIRE_ROD: { category: ItemCategory.Rod },
    HOLLOW_BOOTS: {
        category: ItemCategory.Armor,
        type: ItemType.Boots,
        family: ItemFamily.Kuudra,
    },
    HOLLOW_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
        family: ItemFamily.Kuudra,
    },
    HOLLOW_HELMET: {
        category: ItemCategory.Armor,
        type: ItemType.Helmet,
        family: ItemFamily.Kuudra,
    },
    HOLLOW_LEGGINGS: {
        category: ItemCategory.Armor,
        type: ItemType.Leggings,
        family: ItemFamily.Kuudra,
    },
    HOLLOW_WAND: { category: ItemCategory.Weapon },
    IMPLOSION_BELT: { category: ItemCategory.Equipment, type: ItemType.Belt },
    INFERNO_ROD: { category: ItemCategory.Rod },
    LAVA_SHELL_NECKLACE: {
        category: ItemCategory.Equipment,
        type: ItemType.Necklace,
    },
    MAGMA_LORD_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    MAGMA_LORD_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
    },
    MAGMA_LORD_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    MAGMA_LORD_LEGGINGS: {
        category: ItemCategory.Armor,
        type: ItemType.Leggings,
    },
    MAGMA_NECKLACE: { category: ItemCategory.Armor, type: ItemType.Necklace },
    MAGMA_ROD: { category: ItemCategory.Rod },
    MOLTEN_BELT: {
        category: ItemCategory.Equipment,
        type: ItemType.Belt,
        family: ItemFamily.Molten,
    },
    MOLTEN_BRACELET: {
        category: ItemCategory.Equipment,
        type: ItemType.Bracelet,
        family: ItemFamily.Molten,
    },
    MOLTEN_CLOAK: {
        category: ItemCategory.Equipment,
        type: ItemType.Cloak,
        family: ItemFamily.Molten,
    },
    MOLTEN_NECKLACE: {
        category: ItemCategory.Equipment,
        type: ItemType.Necklace,
        family: ItemFamily.Molten,
    },
    MOOGMA_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    RAGNAROCK_AXE: { category: ItemCategory.Weapon },
    SCOURGE_CLOAK: { category: ItemCategory.Equipment, type: ItemType.Cloak },
    SCOVILLE_BELT: { category: ItemCategory.Equipment, type: ItemType.Belt },
    SHIMMERING_LIGHT_HOOD: {
        category: ItemCategory.Armor,
        type: ItemType.Helmet,
    },
    SHIMMERING_LIGHT_SLIPPERS: {
        category: ItemCategory.Armor,
        type: ItemType.Boots,
    },
    SHIMMERING_LIGHT_TROUSERS: {
        category: ItemCategory.Armor,
        type: ItemType.Leggings,
    },
    SHIMMERING_LIGHT_TUNIC: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
    },
    SLUG_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    STAFF_OF_THE_VOLCANO: { category: ItemCategory.Weapon },
    SULPHUR_BOW: { category: ItemCategory.Bow },
    SWORD_OF_BAD_HEALTH: { category: ItemCategory.Weapon },
    TAURUS_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    TERROR_BOOTS: {
        category: ItemCategory.Armor,
        type: ItemType.Boots,
        family: ItemFamily.Kuudra,
    },
    TERROR_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
        family: ItemFamily.Kuudra,
    },
    TERROR_HELMET: {
        category: ItemCategory.Armor,
        type: ItemType.Helmet,
        family: ItemFamily.Kuudra,
    },
    TERROR_LEGGINGS: {
        category: ItemCategory.Armor,
        type: ItemType.Leggings,
        family: ItemFamily.Kuudra,
    },
    THUNDERBOLT_NECKLACE: {
        category: ItemCategory.Equipment,
        type: ItemType.Necklace,
    },
    THUNDER_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    THUNDER_CHESTPLATE: {
        category: ItemCategory.Armor,
        type: ItemType.Chestplate,
    },
    THUNDER_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    THUNDER_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    VANQUISHED_BLAZE_BELT: {
        category: ItemCategory.Equipment,
        type: ItemType.Belt,
        family: ItemFamily.Vanquished,
    },
    VANQUISHED_GHAST_CLOAK: {
        category: ItemCategory.Equipment,
        type: ItemType.Cloak,
        family: ItemFamily.Vanquished,
    },
    VANQUISHED_GLOWSTONE_GAUNTLET: {
        category: ItemCategory.Equipment,
        type: ItemType.Gloves,
        family: ItemFamily.Vanquished,
    },
    VANQUISHED_MAGMA_NECKLACE: {
        category: ItemCategory.Equipment,
        type: ItemType.Necklace,
        family: ItemFamily.Vanquished,
    },
    WAND_OF_STRENGTH: { category: ItemCategory.Weapon },
};

export const ITEM_EMOJIS: Record<string, string> = {
    ATTRIBUTE_SHARD: '<:ATTRIBUTE_SHARD:1207542330039476265>',
    AURORA_BOOTS: '<:AURORA_BOOTS:1207542331964923964>',
    AURORA_CHESTPLATE: '<:AURORA_CHESTPLATE:1207542333860610088>',
    AURORA_HELMET: '<:AURORA_HELMET:1207542335538335785>',
    AURORA_LEGGINGS: '<:AURORA_LEGGINGS:1207542338654572614>',
    BERSERKER_BOOTS: '<:BERSERKER_BOOTS:1207542340860776459>',
    BERSERKER_CHESTPLATE: '<:BERSERKER_CHESTPLATE:1207542343805304852>',
    BERSERKER_HELMET: '<:BERSERKER_HELMET:1207542345936019476>',
    BLADE_OF_THE_VOLCANO: '<:BLADE_OF_THE_VOLCANO:1207542347714527262>',
    BLAZE_BELT: '<:BLAZE_BELT:1207542349962551316>',
    CRIMSON_BOOTS: '<:CRIMSON_BOOTS:1207542351786934272>',
    CRIMSON_CHESTPLATE: '<:CRIMSON_CHESTPLATE:1207542353490087966>',
    CRIMSON_HELMET: '<:CRIMSON_HELMET:1207542355452887090>',
    CRIMSON_LEGGINGS: '<:CRIMSON_LEGGINGS:1207542357374009415>',
    DELIRIUM_NECKLACE: '<:DELIRIUM_NECKLACE:1207542359387275305>',
    FERVOR_BOOTS: '<:FERVOR_BOOTS:1207542361119527004>',
    FERVOR_CHESTPLATE: '<:FERVOR_CHESTPLATE:1207542363421933588>',
    FERVOR_HELMET: '<:FERVOR_HELMET:1207542365628145704>',
    FERVOR_LEGGINGS: '<:FERVOR_LEGGINGS:1207542367473893407>',
    FIRE_FREEZE_STAFF: '<:FIRE_FREEZE_STAFF:1207542370623561758>',
    FIRE_FURY_STAFF: '<:FIRE_FURY_STAFF:1207542372842606663>',
    FIRE_VEIL_WAND: '<:FIRE_VEIL_WAND:1207542375161798726>',
    FLAMING_CHESTPLATE: '<:FLAMING_CHESTPLATE:1207542377279918120>',
    FLAMING_FIST: '<:FLAMING_FIST:1207542378999578624>',
    GAUNTLET_OF_CONTAGION: '<:GAUNTLET_OF_CONTAGION:1207542381126357133>',
    GHAST_CLOAK: '<:GHAST_CLOAK:1207542383579758623>',
    GLOWSTONE_GAUNTLET: '<:GLOWSTONE_GAUNTLET:1207542385903534170>',
    HELLFIRE_ROD: '<:HELLFIRE_ROD:1207542388097028147>',
    HOLLOW_BOOTS: '<:HOLLOW_BOOTS:1207542390102032424>',
    HOLLOW_CHESTPLATE: '<:HOLLOW_CHESTPLATE:1207542392098525194>',
    HOLLOW_HELMET: '<:HOLLOW_HELMET:1207542393918853121>',
    HOLLOW_LEGGINGS: '<:HOLLOW_LEGGINGS:1207542397022765056>',
    HOLLOW_WAND: '<:HOLLOW_WAND:1207542399489015858>',
    IMPLOSION_BELT: '<:IMPLOSION_BELT:1207542401221271582>',
    INFERNO_ROD: '<:INFERNO_ROD:1207542402852720754>',
    LAVA_SHELL_NECKLACE: '<:LAVA_SHELL_NECKLACE:1207542409844621402>',
    MAGMA_LORD_BOOTS: '<:MAGMA_LORD_BOOTS:1207542412184911882>',
    MAGMA_LORD_CHESTPLATE: '<:MAGMA_LORD_CHESTPLATE:1207542414252707880>',
    MAGMA_LORD_HELMET: '<:MAGMA_LORD_HELMET:1207542416685670450>',
    MAGMA_LORD_LEGGINGS: '<:MAGMA_LORD_LEGGINGS:1207542419097129001>',
    MAGMA_NECKLACE: '<:MAGMA_NECKLACE:1207542421815042068>',
    MAGMA_ROD: '<:MAGMA_ROD:1207542424163844166>',
    MOLTEN_BELT: '<:MOLTEN_BELT:1207542427120963625>',
    MOLTEN_BRACELET: '<:MOLTEN_BRACELET:1207542429649993739>',
    MOLTEN_CLOAK: '<:MOLTEN_CLOAK:1207542432707641414>',
    MOLTEN_NECKLACE: '<:MOLTEN_NECKLACE:1207542434834415717>',
    MOOGMA_LEGGINGS: '<:MOOGMA_LEGGINGS:1207542436725788674>',
    RAGNAROCK_AXE: '<:RAGNAROCK_AXE:1207542438978387978>',
    SCOURGE_CLOAK: '<:SCOURGE_CLOAK:1207542441154973696>',
    SCOVILLE_BELT: '<:SCOVILLE_BELT:1207542443210440724>',
    SHIMMERING_LIGHT_HOOD: '<:SHIMMERING_LIGHT_HOOD:1207542451049472000>',
    SHIMMERING_LIGHT_SLIPPERS:
        '<:SHIMMERING_LIGHT_SLIPPERS:1207542453268254802>',
    SHIMMERING_LIGHT_TROUSERS:
        '<:SHIMMERING_LIGHT_TROUSERS:1207542455633707038>',
    SHIMMERING_LIGHT_TUNIC: '<:SHIMMERING_LIGHT_TUNIC:1207542457621815346>',
    SLUG_BOOTS: '<:SLUG_BOOTS:1207542459555389480>',
    STAFF_OF_THE_VOLCANO: '<:STAFF_OF_THE_VOLCANO:1207542461954789377>',
    SULPHUR_BOW: '<:SULPHUR_BOW:1207542464454459422>',
    SWORD_OF_BAD_HEALTH: '<:SWORD_OF_BAD_HEALTH:1207542466832764968>',
    TAURUS_HELMET: '<:TAURUS_HELMET:1207542468979986442>',
    TERROR_BOOTS: '<:TERROR_BOOTS:1207542471085789194>',
    TERROR_CHESTPLATE: '<:TERROR_CHESTPLATE:1207542473170354247>',
    TERROR_HELMET: '<:TERROR_HELMET:1207542475913429012>',
    TERROR_LEGGINGS: '<:TERROR_LEGGINGS:1207542477972570173>',
    THUNDER_BOOTS: '<:THUNDER_BOOTS:1207542480145358858>',
    THUNDER_CHESTPLATE: '<:THUNDER_CHESTPLATE:1207542482116542534>',
    THUNDER_HELMET: '<:THUNDER_HELMET:1207542484285005895>',
    THUNDER_LEGGINGS: '<:THUNDER_LEGGINGS:1207542486466301972>',
    THUNDERBOLT_NECKLACE: '<:THUNDERBOLT_NECKLACE:1207542488873828432>',
    VANQUISHED_BLAZE_BELT: '<:VANQUISHED_BLAZE_BELT:1207542490748555314>',
    VANQUISHED_GHAST_CLOAK: '<:VANQUISHED_GHAST_CLOAK:1207542493172863018>',
    VANQUISHED_GLOWSTONE_GAUNTLET:
        '<:VANQUISHED_GLOWSTONE_GAUNTLET:1207542495450234880>',
    VANQUISHED_MAGMA_NECKLACE:
        '<:VANQUISHED_MAGMA_NECKLACE:1207542518942797824>',
    WAND_OF_STRENGTH: '<:WAND_OF_STRENGTH:1207542521081757746>',
};

export const MISC_EMOJIS: Record<string, string> = {
    COIN: '<:COIN:1207544192801185804>',
};
