export enum ItemCategory {
    Shard = "SHARD",
    Armor = "ARMOR",
    Weapon = "WEAPON",
    Sword = "SWORD",
    Bow = "BOW",
    Equipment = "EQUIPMENT",
    Rod = "ROD",
}

export enum ItemType {
    Helmet = "HELMET",
    Chestplate = "CHESTPLATE",
    Leggings = "LEGGINGS",
    Boots = "BOOTS",
    Necklace = "NECKLACE",
    Cloak = "CLOAK",
    Belt = "BELT",
    Gloves = "GLOVES",
    Bracelet = "BRACELET",
}

export const ATTRIBUTE_MAPPINGS = {
    'mp': 'mana_pool',
    'fs': 'fishing_speed',
    'fe': 'fishing_experience',
    'th': 'trophy_hunter',
    'dh': 'double_hook',
    'bh': 'blazing_fortune',
    'mr': 'mana_regeneration',
    'mf': 'magic_find',
    'dom': 'dominance',
    'vit': 'vitality',
    'vet': 'veteran',
    'll': 'lifeline',
};

export const ITEM_METADATA: Record<string, { category: ItemCategory, type?: ItemType }> = {
    ATTRIBUTE_SHARD: { category: ItemCategory.Shard },
    AURORA_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    AURORA_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    AURORA_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    AURORA_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    BERSERKER_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    BERSERKER_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    BERSERKER_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    BERSERKER_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    BLADE_OF_THE_VOLCANO: { category: ItemCategory.Weapon },
    BLAZE_BELT: { category: ItemCategory.Equipment, type: ItemType.Belt },
    CRIMSON_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    CRIMSON_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    CRIMSON_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    CRIMSON_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    DELIRIUM_NECKLACE: { category: ItemCategory.Equipment, type: ItemType.Necklace },
    FERVOR_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    FERVOR_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    FERVOR_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    FERVOR_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Boots },
    FIRE_FREEZE_STAFF: { category: ItemCategory.Weapon },
    FIRE_FURY_STAFF: { category: ItemCategory.Weapon },
    FIRE_VEIL_WAND: { category: ItemCategory.Weapon },
    FLAMING_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    FLAMING_FIST: { category: ItemCategory.Equipment, type: ItemType.Gloves },
    GAUNTLET_OF_CONTAGION: { category: ItemCategory.Equipment, type: ItemType.Gloves },
    GHAST_CLOAK: { category: ItemCategory.Equipment, type: ItemType.Cloak },
    GLOWSTONE_GAUNTLET: { category: ItemCategory.Equipment, type: ItemType.Gloves },
    HELLFIRE_ROD: { category: ItemCategory.Rod },
    HOLLOW_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    HOLLOW_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    HOLLOW_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    HOLLOW_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    HOLLOW_WAND: { category: ItemCategory.Weapon },
    IMPLOSION_BELT: { category: ItemCategory.Equipment, type: ItemType.Belt },
    INFERNO_ROD: { category: ItemCategory.Rod },
    LAVA_SHELL_NECKLACE: { category: ItemCategory.Equipment, type: ItemType.Necklace },
    MAGMA_LORD_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    MAGMA_LORD_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    MAGMA_LORD_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    MAGMA_LORD_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    MAGMA_NECKLACE: { category: ItemCategory.Armor, type: ItemType.Necklace },
    MAGMA_ROD: { category: ItemCategory.Rod },
    MOLTEN_BELT: { category: ItemCategory.Equipment, type: ItemType.Belt },
    MOLTEN_BRACELET: { category: ItemCategory.Equipment, type: ItemType.Bracelet },
    MOLTEN_CLOAK: { category: ItemCategory.Equipment, type: ItemType.Cloak },
    MOLTEN_NECKLACE: { category: ItemCategory.Equipment, type: ItemType.Necklace },
    MOOGMA_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    RAGNAROCK_AXE: { category: ItemCategory.Weapon },
    SCOURGE_CLOAK: { category: ItemCategory.Equipment, type: ItemType.Cloak },
    SCOVILLE_BELT: { category: ItemCategory.Equipment, type: ItemType.Belt },
    SHIMMERING_LIGHT_HOOD: { category: ItemCategory.Armor, type: ItemType.Helmet },
    SHIMMERING_LIGHT_SLIPPERS: { category: ItemCategory.Armor, type: ItemType.Boots },
    SHIMMERING_LIGHT_TROUSERS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    SHIMMERING_LIGHT_TUNIC: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    SLUG_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    STAFF_OF_THE_VOLCANO: { category: ItemCategory.Weapon },
    SULPHUR_BOW: { category: ItemCategory.Bow },
    SWORD_OF_BAD_HEALTH: { category: ItemCategory.Weapon },
    TAURUS_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    TERROR_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    TERROR_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    TERROR_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    TERROR_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    THUNDERBOLT_NECKLACE: { category: ItemCategory.Equipment, type: ItemType.Necklace },
    THUNDER_BOOTS: { category: ItemCategory.Armor, type: ItemType.Boots },
    THUNDER_CHESTPLATE: { category: ItemCategory.Armor, type: ItemType.Chestplate },
    THUNDER_HELMET: { category: ItemCategory.Armor, type: ItemType.Helmet },
    THUNDER_LEGGINGS: { category: ItemCategory.Armor, type: ItemType.Leggings },
    VANQUISHED_BLAZE_BELT: { category: ItemCategory.Equipment, type: ItemType.Belt },
    VANQUISHED_GHAST_CLOAK: { category: ItemCategory.Equipment, type: ItemType.Cloak },
    VANQUISHED_GLOWSTONE_GAUNTLET: { category: ItemCategory.Equipment, type: ItemType.Gloves },
    VANQUISHED_MAGMA_NECKLACE: { category: ItemCategory.Equipment, type: ItemType.Necklace },
    WAND_OF_STRENGTH: { category: ItemCategory.Weapon }
};